import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/react-query.provider";
import { Toaster } from "react-hot-toast";
import { AuthHydrator } from "@/providers/auth.hydrator";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <ReactQueryProvider>
          <AuthHydrator>{children}</AuthHydrator>
        </ReactQueryProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
